apiVersion: v1
kind: ConfigMap
metadata:
  name: shop-config
data:
  DB_HOST: "mysql-service"
  DB_PORT: "{{ .Values.mysql.port }}"
  DB_NAME: {{ .Values.mysql.database }}
  DB_USER: {{ .Values.mysql.user }}
  REDIS_HOST: "redis-service"
  REDIS_PORT: "{{ .Values.redis.port }}"
