apiVersion: v1
kind: Secret
metadata:
  name: shop-secret
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: {{ .Values.mysql.rootPassword }}
  MYSQL_PASSWORD: {{ .Values.mysql.password }}
  DB_PASSWORD: {{ .Values.mysql.password }}
  JWT_SECRET: {{ .Values.jwt.secret }}
