apiVersion: v1
kind: ConfigMap
metadata:
  name: shop-config
data:
  DB_HOST: "mysql-service"
  DB_PORT: "3306"
  DB_NAME: "shopdb"
  DB_USER: "shopuser"
  REDIS_HOST: "redis-service"
  REDIS_PORT: "6379"
