apiVersion: v1
kind: Secret
metadata:
  name: shop-secret
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: "rootpass"
  MYSQL_PASSWORD: "shoppass"
  DB_PASSWORD: "shoppass"
  JWT_SECRET: "k8s-shop-jwt-secret-2024"
